sylius_shop_api_cart:
    resource: "@ShopApiPlugin/Resources/config/routing/cart.yml"
    prefix: /shop-api/{channelCode}

sylius_shop_api_checkout:
    resource: "@ShopApiPlugin/Resources/config/routing/checkout.yml"
    prefix: /shop-api/{channelCode}/checkout

sylius_shop_api_address_book:
    resource: "@ShopApiPlugin/Resources/config/routing/address_book.yml"
    prefix: /shop-api/{channelCode}

sylius_shop_api_order:
    resource: "@ShopApiPlugin/Resources/config/routing/order.yml"
    prefix: /shop-api/{channelCode}
