jms_serializer:
    metadata:
        directories:
            sylius-shop-api-taxon:
                namespace_prefix: "Sylius\\ShopApiPlugin\\View\\Taxon"
                path: "@ShopApiPlugin/Resources/config/serializer/Taxon"
            sylius-shop-api-product:
                namespace_prefix: "Sylius\\ShopApiPlugin\\View\\Product"
                path: "@ShopApiPlugin/Resources/config/serializer/Product"

sylius_customer:
    resources:
        customer:
            classes:
                controller: Sylius\ShopApiPlugin\Controller\Customer\CustomerController
