# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_mailer:
    emails:
        shop_api_verification_token:
            subject: sylius.emails.user.verification_token.subject
            template: '@ShopApiPlugin/verification_email.html.twig'
        shop_api_reset_password_token:
            subject: sylius.emails.user.password_reset.subject
            template: '@ShopApiPlugin/password_reset_email.html.twig'
